name: Create Issue

on:
  workflow_dispatch:
    inputs:
      repository:
        description: 'Repository Name'
        required: true
      title:
        description: 'Issue Title'
        required: true
      body:
        description: 'Issue Body'
        required: true
      assignee:
        description: 'Issue Assignee'
        required: false

jobs:
  create-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Create Issue
        uses: octokit/request-action@v2.x
        with:
          route: POST /repos/xdeli-tech/${{ github.event.inputs.repository }}/issues
          mediaType: |
            previews:
              - symmetra
        env:
          GITHUB_TOKEN: ${{ secrets.XDELI_BOT_TOKEN }}
          ISSUE_TITLE: ${{ github.event.inputs.title }}
          ISSUE_BODY: ${{ github.event.inputs.body }}
          ISSUE_ASSIGNEES: ${{ github.event.inputs.assignee }}
