name: Create Issue

on:
  workflow_dispatch:
    inputs:
      repository:
        description: 'Repository Name'
        required: true
      title:
        description: 'Issue Title'
        required: true
      body:
        description: 'Issue Body'
        required: true
      assignee:
        description: 'Issue Assignee'
        required: false

jobs:
  create-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Create Issue
        run: |
          curl -f -X POST \
            -H "Authorization: token ${{ secrets.XDELI_BOT_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            -d '{"title":"${{ github.event.inputs.title }}","body":"${{ github.event.inputs.body }}","assignees":["${{ github.event.inputs.assignee }}"]}' \
            https://api.github.com/repos/xdeli-tech/${{ github.event.inputs.repository }}/issues
