name: Move new issues & PR into Unread

on:
  issues:
    types: [opened, assigned, unassigned]
  pull_request:
    types: [opened, assigned, unassigned]

env:
  backlog: 📋 Backlog
  unread: 📥 Unread
  gh_project_token: ${{ secrets.XDELI_BOT_TOKEN }}
  org: xdeli-tech
  project_id: 3

jobs:
  move_to_unread:
    runs-on: ubuntu-latest
    timeout-minutes: 1
    steps:
      - name: Move issue to ${{ env.unread }}
        uses: leonsteinhaeuser/project-beta-automations@v2.2.1
        with:
          gh_token: ${{ env.gh_project_token }}
          organization: ${{ env.org }}
          project_id: ${{ env.project_id }}
          resource_node_id: ${{ github.event.pull_request.node_id || github.event.issue.node_id }}
          status_value: ${{ env.unread }}
