name: Assign Author on Change Request

on:
  pull_request_review:
    types: [submitted]

jobs:
  assign-author:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Assign PR Author
        if: github.event.review.state == 'changes_requested'
        uses: peter-evans/create-or-update-comment@v1
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            @${{ github.event.pull_request.user.login }} への変更リクエストがあります。
          assignees: |
            ${{ github.event.pull_request.user.login }}
