name: Assign Author on Change Request

on:
  pull_request_review:
    types: [submitted]

jobs:
  assign-author:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Assign PR Author if Changes Requested
        if: github.event.review.state == 'changes_requested'
        uses: actions/github-script@v5
        with:
          script: |
            github.rest.issues.addAssignees({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.payload.pull_request.number,
              assignees: [context.payload.pull_request.user.login]
            });
