name: Assign PR Author on Change Request

on:
  pull_request_review:
    types: [submitted]

jobs:
  assign-author:
    if: github.event.review.state == 'changes_requested'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get First Commit Author
        id: get-author
        run: |
          FIRST_COMMIT_SHA=$(git rev-list --max-parents=0 HEAD)
          AUTHOR_LOGIN=$(git show -s --format='%an <%ae>' $FIRST_COMMIT_SHA)
          echo "::set-output name=author_login::$AUTHOR_LOGIN"

      - name: Print and Unassign all assignees
        run: |
          echo "Fetching current assignees..."
          ASSIGNEES_JSON=$(curl -H "Authorization: token ${{ secrets.XDELI_BOT_TOKEN }}" \
          "https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/assignees")
          echo "Current Assignees: $ASSIGNEES_JSON"

          ASSIGNEES=$(echo "$ASSIGNEES_JSON" | jq -r '.[].login')
          echo "Assignee Logins: $ASSIGNEES"

          for assignee in $ASSIGNEES; do
            echo "Unassigning $assignee..."
            UNASSIGN_RESULT=$(curl -X DELETE -H "Authorization: token ${{ secrets.XDELI_BOT_TOKEN }}" \
            "https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/assignees" \
            -d "{\"assignees\": [\"$assignee\"]}")
            echo "Unassign Result for $assignee: $UNASSIGN_RESULT"
          done
  
  
      - name: Assign First Commit Author as Assignee
        run: |
          curl -X POST -H "Authorization: token ${{ secrets.XDELI_BOT_TOKEN }}" \
          "https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/assignees" \
          -d '{"assignees": ["${{ steps.get-author.outputs.author_login }}"]}'
