name: Assign PR Author on Change Request

on:
  pull_request_review:
    types: [submitted]

jobs:
  assign-author:
    if: github.event.review.state == 'changes_requested'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get First Commit Author
        id: get-author
        run: |
          FIRST_COMMIT_SHA=$(git rev-list --max-parents=0 HEAD)
          AUTHOR_LOGIN=$(git show -s --format='%an <%ae>' $FIRST_COMMIT_SHA)
          echo "::set-output name=author_login::$AUTHOR_LOGIN"

      - name: print Unassign all assignees
        run: |
          curl -H "Authorization: token ${{ secrets.XDELI_BOT_TOKEN }}" \
          "https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/assignees"
          curl -H "Authorization: token ${{ secrets.XDELI_BOT_TOKEN }}" \
          "https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/assignees" | jq -r '.[] 
      - name: Unassign all assignees
        run: |
          ASSIGNEES=$(curl -H "Authorization: token ${{ secrets.XDELI_BOT_TOKEN }}" \
          "https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/assignees" | jq -r '.[] | .login')
          for assignee in $ASSIGNEES; do
            curl -X DELETE -H "Authorization: token ${{ secrets.XDELI_BOT_TOKEN }}" \
            "https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/assignees" \
            -d "{\"assignees\": [\"$assignee\"]}"
          done

      - name: Assign First Commit Author as Assignee
        run: |
          curl -X POST -H "Authorization: token ${{ secrets.XDELI_BOT_TOKEN }}" \
          "https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/assignees" \
          -d '{"assignees": ["${{ steps.get-author.outputs.author_login }}"]}'
